FROM node:current-alpine3.17 AS build

WORKDIR /client

COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM node:current-alpine3.17

WORKDIR /client
COPY --from=build /client/build /client

RUN npm install -g serve

EXPOSE 80
CMD ["serve", "/client", "-l", "80"]
