apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
type: Opaque
data:
  # The following values are in base64 as per k8 secret spec
  # They will automatically be decoded upon retrieval 
  # The following will convert text to base64: echo -n 'someText' | base64
  SECRET: TXlTdXBlckR1cGVyU2VjcmV0 # MySuperDuperSecret
  NESTED.SECRET: TXlOZXN0ZWRTZWNyZXQ= # MyNestedSecret
  database.password: c2VjdXJlUGFzc3dvcmQ= # securePassword