kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8-mini-app-server
spec:
  replicas: 2 # This should be at least 2 if you want to see the /pod route working
  selector:
    matchLabels:
      app: k8-mini-app-server
  template:
    metadata:
      labels:
        app: k8-mini-app-server
    spec:
      containers:
        - name: server
          image:  # your image here
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http-server
          env:
            # Import variable from the pods
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  # this gets the pod name so we can return it via the /pod route
                  fieldPath: metadata.name
            - name: postgres-service-name
              value: postgres-svc # this is the name that we've listed for the postgres service (metadata.name)
          envFrom:
            - secretRef:  
                name: server-secrets
---
# Server service (so that the server can be access - in this case by the client)
apiVersion: v1
kind: Service
metadata:
  name: k8-mini-app-server
spec:
  selector:
    app: k8-mini-app-server
  ports:
    - port: 80
      targetPort: http-server # this references the server deployment pod ports.name