apiVersion: v1
kind: Service
metadata:
  name: k8-mini-app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    # This selects the deployment to use (thus must match pec.selector.matchLabels.app of the deployment)
    app: k8-mini-app-server
  ports:
    - port: 80 # Service Port
      targetPort: 8080 # Container Port
