kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8-mini-app-client
spec:
  replicas: 2 # This should be at least 2 if you want to see the /pod route working
  selector:
    matchLabels:
      app: k8-mini-app-client
  template:
    metadata:
      labels:
        app: k8-mini-app-client
    spec:
      containers:
        - name: client
          image: k8-mini-app-client # your image here
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http-client
---
# Server service
apiVersion: v1
kind: Service
metadata:
  name: k8-mini-app-client
spec:
  type: NodePort
  selector:
    name: k8-mini-app-client
  ports:
    - port: 80
      targetPort: http-client