apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8-mini-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        # host: # If you own a domain name uncomment this and add it here
        paths:
          - path: /(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: k8-mini-app-client-service # This is a reference to the client service
                port:
                  number: 80
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: k8-mini-app-server-service # This is a reference to the server service
                port:
                  number: 80